build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.19"
  amd64: "ghcr.io/home-assistant/amd64-base:3.19"
  armhf: "ghcr.io/home-assistant/armhf-base:3.19"
  armv7: "ghcr.io/home-assistant/armv7-base:3.19"  
  i386: "ghcr.io/home-assistant/i386-base:3.19"
labels:
  org.opencontainers.image.title: "Virtual Audio Bridge"
  org.opencontainers.image.description: "Creates virtual audio sinks that stream to network devices via HTTP"
  org.opencontainers.image.source: "https://github.com/synssins/homeassistant-virtual-audio-bridge"
  org.opencontainers.image.licenses: "MIT"
args:
  TEMPIO_VERSION: "2021.09.0"